### ISSUE TITLE
Not able to run on Ubuntu system

### ISSUE THREAD

**Issue by talkingwallace** [zzd1992/GBDTMO-EX#1]
After installing following the guide, I ran the example codes and got this as a return. It seems that the root of the error is located in the set_bin function from 'booster.cpp'.
![image](https://user-images.githubusercontent.com/10768970/121008413-8e035580-c7c5-11eb-8c35-0fd346603d64.png)

**Comment by talkingwallace** [comment]
![image](https://user-images.githubusercontent.com/10768970/121008877-0ec25180-c7c6-11eb-8f80-734513f19893.png)
This is what I got by tracking using gdb.

**Comment by zzd1992** [comment]
This is odd. 
There is a python warpper in `gbdtmo/gbdtmo.py`.
```
def _set_bin(self, bins):
```
You can check the value of `bins`. It should be a list of `np.array`. ith element is the histogram bin for ith column. 
And I hope you provide the full backtrace for better debug.

**Comment by talkingwallace** [comment]
Thanks, I ll check it later

**Comment by talkingwallace** [comment]
It seems that the input is OK. This is the code, program corrupted at this line:
![image](https://user-images.githubusercontent.com/10768970/121116559-52aa6a80-c849-11eb-894d-1b0c5311f210.png)
Then I check '_set_bin' functions, the list length and bin number looks fine:
![image](https://user-images.githubusercontent.com/10768970/121116675-7cfc2800-c849-11eb-9760-14a00d95accc.png)
![image](https://user-images.githubusercontent.com/10768970/121116686-838a9f80-c849-11eb-897f-89a206a486c1.png)
Then I trackback to the C++ origin codes, I found out that when executing this line, the whole program stop:
![image](https://user-images.githubusercontent.com/10768970/121117056-1fb4a680-c84a-11eb-84de-fdd8f129f1e3.png)
I am wondering if there is any method to throw an C++ exception which gives details about the errors when I call the library in python.

**Comment by zzd1992** [comment]
There are some test codes in `src/main.cpp`.
I think you can compile it and debug it directly in c++.

For example, in `src/main.cpp`, I set `bins` and `values` manually.
```c
uint16_t bins[inp_dim];    
double values[inp_dim * 19];    
for (int i = 0; i &lt; inp_dim; i++) {        
    bins[i] = 19;        
    for (int j = 0; j &lt; 19; j++) { values[i * 19 + j] = (j + 1) / 20.0f; }    
}
```

Then I run `BoosterUtils::set_bin(bins, values)`.

**Comment by talkingwallace** [comment]
Greeting, I tried to compile the C++ source codes, and I can run the examples in the main.cpp. However, the python library is still not usable, it corrupted when the "set_bin" is called. 

And I try to modify the C++ program: I loaded data I needed for training a GBDTMO tree in main.cpp, however, when I call the "train" function, the program corrupted again. And I got similar feedback:
![image](https://user-images.githubusercontent.com/10768970/122029649-a09e1000-cdff-11eb-8c02-a8ae7e9a130c.png)

Now I packed the whole project in my computer, including compiled .so file, and compiled main.cpp( executable is "test" under src folder). Here's the link:
https://drive.google.com/file/d/1L5PJv67pV6J0ckdyn3PhehnS_S6R_bFn/view?usp=sharing

I hope this can help to reproduce the error and find out the problem.

**Comment by zzd1992** [comment]
I will look at it carefully.

But when I run the following test script using your compiled .so file, everything looks fine.
```python
from gbdtmo import GBDTMulti, load_lib
import numpy as np

LIB = load_lib("build/gbdtmo.so")
inp_dim, out_dim = 10, 5
params = {"max_depth": 5, "lr": 0.1, 'loss': b"mse"}
booster = GBDTMulti(LIB, out_dim=out_dim, params=params)

x_train, y_train = np.random.rand(10000, inp_dim), np.random.rand(10000, out_dim)
x_valid, y_valid = np.random.rand(10000, inp_dim), np.random.rand(10000, out_dim)
booster.set_data((x_train, y_train), (x_valid, y_valid))
booster.train(10)
```
The output of this code is
```
init done
10
5
going setting
0
visiting variable
10
setting data
setting data done
visiting variable donetohere[0] train->0.53620	eval->0.53443
[1] train->0.49873	eval->0.49715
[2] train->0.46625	eval->0.46491
[3] train->0.43816	eval->0.43693
[4] train->0.41392	eval->0.41297
[5] train->0.39309	eval->0.39235
[6] train->0.37543	eval->0.37482
[7] train->0.36045	eval->0.36002
[8] train->0.34783	eval->0.34758
[9] train->0.33720	eval->0.33710
Best score 0.33710 at round 9
```

Could you check this script again and show some information about your computer system which may be a matter?

**Comment by talkingwallace** [comment]
Thanks for your prompt reply. Executing the "test" file under the "src" folder is also OK in your environment? 
I think this problem is caused by the python environment or the system environment, would you mind offering details of the Ubuntu version and the python environment you are currently using?

**Comment by zzd1992** [comment]
The "test" file is not ok.
```
out_dim is 4
input dim is 18 sample num is 846
init done
18
3
tohere
tree initialization done
double free or corruption (out)
Aborted (core dumped)
```
But it is ok to run a random dataset. So I think your own dataset may be problematic.
Currently, I work on Python 3.6 and Ubuntu 18.04.
I also have tested my program on Ubuntu14.04 and 16.04.
Other Python version is not tested.

**Comment by talkingwallace** [comment]
Thanks, I'll test in a new environment.

**Comment by talkingwallace** [comment]
Hi, I try again on a pure native ubuntu python-3 environment, and it works fine. The error may caused by using miniconda/anaconda. Thanks for your suppor. : D
