### ISSUE TITLE
Session crashes after running the model

### ISSUE THREAD

**Issue by samanemami** [zzd1992/GBDTMO-EX#2]
Dear @zzd1992 

I managed to import the model. But when I train the model, it will restart my whole session and does not work without printing any error.

I wrote the code in this [gist](https://gist.github.com/samanemami/5d0aefe4a6286ab07fd69370dec24d97).

Thank you in advance

**Comment by zzd1992** [comment]
Thanks for your interest.
But I can't access your gist.
You can run a toy example to check whether GBDTMO works well. For example,
```python
from gbdtmo import GBDTMulti, load_lib

LIB = load_lib("path to gbdtmo.so")
inp_dim, out_dim = 10, 5
params = {"max_depth": 5, "lr": 0.1, 'loss': b"mse"}
booster = GBDTMulti(LIB, out_dim=out_dim, params=params)

x_train, y_train = np.random.rand(10000, inp_dim), np.random.rand(10000, out_dim)
x_valid, y_valid = np.random.rand(10000, inp_dim), np.random.rand(10000, out_dim)
booster.set_data((x_train, y_train), (x_valid, y_valid))
booster.train(30)
booster.dump(b"tree.txt")
```

**Comment by samanemami** [comment]
Thank you for your reply and support @zzd1992 

I share the [gist](https://colab.research.google.com/drive/1uRlrQ1k6uvO3BAU1FgKZCfmMqyORMofe?usp=sharing) with your ID.
I have done with the exact toy dataset, it did not work.

I am running the model on Google colab, as I could not solve [this](https://github.com/zzd1992/GBDTMO/issues/3#issuecomment-920223167) problem.
If you can help me to solve [this](https://github.com/zzd1992/GBDTMO/issues/3#issuecomment-920223167) problem on my PC, I could run a python Debug.

I appreciate your help.

**Comment by samanemami** [comment]
I tested it on Linux and it is working fine.
Thank you @zzd1992

**Comment by samanemami** [comment]
I tested it on Linux and it is working fine.
Thank you @zzd1992
