### ISSUE TITLE
Idea> is there any way to optimize hyper parameters with sklearn.gridsearchCV

### ISSUE THREAD

**Issue by samanemami** [zzd1992/GBDTMO-EX#3]
I am training the [GBDTMO](https://github.com/zzd1992/GBDTMO) model and I want to have the optimized hyperparameters so I was thinking to implement [Gridsearchcv](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html) but it is not compatible with GBDTMO.
Is there any feature to work with GridsearchCV?

Thank you in advance

**Comment by zzd1992** [comment]
You can implement grid search on your own. 
Each time, you build a new GBDTMO instance with different parameters.

Or you can build a wrapper of GBDTMO which acts like built-in estimators of sklearn. And then pass it to Gridsearchcv.

I personally prefer the first solution.
