### ISSUE TITLE
train/test score

### ISSUE THREAD

**Issue by samanemami** [zzd1992/GBDTMO-EX#5]
Dear @zzd1992 

If I understood correctly, you trained the mode through the following method;
```Python
def set_data(self, train_set: tuple = None, eval_set: tuple = None):
	pass
```
If so, the score in the example would be the training score, or I miss some part of model training and evaluation.

It would be great to have your opinion about my point of view.

Thanks in advance

**Comment by zzd1992** [comment]
This method is used to initialize datasets.
If `eval_set` is `None`, only the training score is calculated.
If it is not `None`, then both the training score and evaluation metric will be calculated.

The training method is here
```
def train(self, num):
        self.lib.Train(self._boostnode, num)
```

**Comment by samanemami** [comment]
So if I include the `eval_set` as well, is the returned score (for instance, `mse`) is test score?
Also, In the case of regression, the `mse` would be the average of all outputs? as each output, has its error.

**Comment by zzd1992** [comment]
Yes, the results are the summary of all samples.
For `mse`, the result is averaged.

In fact, for each type of loss function, I set its training score and eval metric. 
You can see details in `src/loss.h`.

If you want error information for each sample, you can first run `predict` method.

**Comment by samanemami** [comment]
I tested this theory that if we do not consider test split in the set_data, it returns the training score, which I think is no difference between returning the test score in any case (f we consider the test in set_data or not).

I collected my brief experiment in this [Notebook](https://github.com/samanemami/GBDTMO/blob/master/Examples/MSE_example.ipynb).
