### ISSUE TITLE
Optimizing the model through the bash file

### ISSUE THREAD

**Issue by samanemami** [zzd1992/GBDTMO-EX#9]
Due to the memory [issue](https://github.com/zzd1992/GBDTMO/issues/12), I am trying to optimize the model through the bash by training the model with different iteration, which I defined the loop in the bash file.
The issue comes after the first iteration, and the model starts to train and never ends.
Any idea?

Check out the bash, here;

```Bash
#!/bin/bash

for lr in 0.025 0.05 
do
      python3 model.py $lr $dp
done
```

**Comment by zzd1992** [comment]
What does "never ends" mean?
The training takes a long time or 
the training is finished but the next iteration doesn't begin?

**Comment by zzd1992** [comment]
Does the number of boost rounds surpass the predefined parameter?

**Comment by samanemami** [comment]
> What does "never ends" mean? The training takes a long time or the training is finished but the next iteration doesn't begin?

The first iteration of training will finish, but the next one won't start.

**Comment by samanemami** [comment]
> Does the number of boost rounds surpass the predefined parameter?

Yes, This is the training part;

```Python
params = {"max_depth": depth, "lr": lr, 'loss': loss,
              'verbose': False, 'subsample': 1.0}

booster = GBDTMulti(LIB, out_dim=n_class, params=params)

booster.set_data((x_train, y_train))
booster.train(50)
```

**Comment by zzd1992** [comment]
This is strange.
I have used the similar way to tune the parameters and it works well.
Could you show the terminal outputs?

**Comment by samanemami** [comment]
The terminal does not return any output!. I was also looking for traceback.

It only prints whatever you want for the first epoch.
Could you please share a `gist` of your `bash` and `py` script, please?

**Comment by samanemami** [comment]
@zzd1992 Do you know any method inside the model so we can unload the LIB after the training?

**Comment by zzd1992** [comment]
@samanemami 
I add examples to GBDTMO library.
Please check it [here](https://github.com/zzd1992/GBDTMO/tree/master/examples)

**Comment by samanemami** [comment]
Thanks for the bash script @zzd1992 
The problem either comes from loading the dynamic library or dataset.
For instance, it does not work on the iris dataset.

```Python
import sklearn.datasets as dts

X, y = dts.load_iris(return_X_y=True)
X, y = np.ascontiguousarray(X, dtype=np.float64), y.astype('int32)
```

**Comment by samanemami** [comment]
I Could not solve the issue.

**Comment by zzd1992** [comment]
I am sorry but I need more information to locate the problem.

"Do you know any method inside the model so we can unload the LIB after the training?"

In my opinion, this is unnecessary. After training, you can build a new `GBDTMO` instance and train it with new parameters.
